version = 1

[[annotations]]
path = "xx-session-management-v1.xml"
precedence = "closest"
SPDX-FileCopyrightText = [
    "Copyright 2018 Mike Blumenkrantz",
    "Copyright 2018 Samsung Electronics Co., Ltd",
    "Copyright 2018 Red Hat Inc."
]

SPDX-License-Identifier = "MIT"
